name: Zip VCS plugins
agent:
  type: Unity::VM
  image: slough-ops/ubuntu-22.04-base:latest
  flavor: b1.small

commands:
  - mkdir linux64
  - cp Build/linux64/* linux64

  - mkdir OSX
  - cp Build/OSX/* OSX

  - mkdir Win32
  - cp Build/Win32/*  Win32

artifacts:
  builds:
    paths:
      - "linux64/**"
      - "OSX/**"
      - "Win32/**"

dependencies:
  - .yamato/linux-build.yml
  - .yamato/osx-build.yml
  - .yamato/windows-build.yml

triggers:
  branches:
    only:
      - "/.*/"
